version: '2'
services:
  web:
    image: codeupgirl
    build: .
    container_name: freeCodeCamp_Scrapper
    entrypoint: /usr/local/bin/python server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
